//// ViewController.swift
//import UIKit
//import AgoraRtcKit
//
//class ViewController: UIViewController {
//    // Declare a variable for the AgoraRtcEngineKit instance
//    var agoraKit: AgoraRtcEngineKit!
//
//    override func viewDidLoad() {
//        super.viewDidLoad()
//        // Initialize the AgoraRtcEngineKit instance with your App ID and and set the delegate to self
//        agoraKit = AgoraRtcEngineKit.sharedEngine(withAppId:"85346947a1ea4fb28109d090d3e1ec50", delegate: self)
//        joinChannel()
//    }
//
//    deinit {
//        agoraKit.leaveChannel(nil)
//        AgoraRtcEngineKit.destroy()
//    }
//    func joinChannel() {
//        let options = AgoraRtcChannelMediaOptions()
//        options.channelProfile = .communication
//        // Set user role to broadcaster; to set user role to audience, keep the default value
//        options.clientRoleType = .broadcaster
//        // Publish microphone audio
//        options.publishMicrophoneTrack = true
//        // Automatically subscribe to all audio streams
//        options.autoSubscribeAudio = true
//        // Join the channel using a temporary token and channel name
//        // If you set the uid of 0, a value is randomly generated by the engine; success triggers the didJoinChannel callback
//        agoraKit.joinChannel(byToken: "007eJxTYHgfO73838vmX1unHM9vcRVcayL8aJ+KwD2HCN7Xup0/KuQUGCxMjU3MLE3MEw1TE03SkowsDA0sUwwsDVKMUw1Tk00NFnmcTGsIZGR4suEbEyMDBIL4LAwZiSWpDAwAvNIhIg==", channelId: "hate", uid: 0, mediaOptions: options)
//    }
//}
//
//extension ViewController: AgoraRtcEngineDelegate {
//    // Callback when the local user successfully joins a channel
//    func rtcEngine(
//        _ engine: AgoraRtcEngineKit, didJoinChannel channel: String, withUid uid: UInt, elapsed: Int
//    ) {
//        print("didJoinChannel: (channel), uid: (uid)")
//    }
//
//    // Callback when a remote user joins the current channel
//    func rtcEngine(_ engine: AgoraRtcEngineKit, didJoinedOfUid uid: UInt, elapsed: Int){
//        // Print debug information
//        print("User (uid) joined after (elapsed) milliseconds")
//    }
//
//    // Callback when a remote user leaves the current channel
//    func rtcEngine(
//        _ engine: AgoraRtcEngineKit, didOfflineOfUid uid: UInt, reason: AgoraUserOfflineReason
//    ) {
//    }
//}
